insert into errors (code, normalized_code, name, title, description, category, severity, aliases, seo_title, seo_description, status, created_at, updated_at) values
('0x80070002', '80070002', 'File Not Found', 'Erro 0x80070002: Arquivo não encontrado', 'Este erro ocorre quando um arquivo necessário não pode ser encontrado.', 'Windows Update', 'alta', '{}', '0x80070002: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x80070002 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x80070003', '80070003', 'Path Not Found', 'Erro 0x80070003: Caminho não encontrado', 'Este erro indica que o caminho especificado não pode ser encontrado.', 'Windows Update', 'alta', '{}', '0x80070003: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x80070003 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x80070005', '80070005', 'Access Denied', 'Erro 0x80070005: Acesso negado', 'Este erro ocorre quando o acesso a um recurso é negado.', 'Windows Update', 'alta', '{}', '0x80070005: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x80070005 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x8007000E', '8007000E', 'Out of Memory', 'Erro 0x8007000E: Memória insuficiente', 'Este erro indica que não há memória suficiente para concluir a operação.', 'Windows Update', 'alta', '{}', '0x8007000E: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x8007000E e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x80070057', '80070057', 'Parameter Incorrect', 'Erro 0x80070057: Parâmetro incorreto', 'Este erro ocorre quando um parâmetro fornecido é inválido.', 'Windows Update', 'alta', '{}', '0x80070057: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x80070057 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x80070422', '80070422', 'Service Disabled', 'Erro 0x80070422: Serviço desativado', 'Este erro indica que um serviço necessário está desativado.', 'Windows Update', 'alta', '{}', '0x80070422: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x80070422 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x800705B4', '800705B4', 'Timeout', 'Erro 0x800705B4: Tempo esgotado', 'Este erro ocorre quando uma operação leva muito tempo para ser concluída.', 'Windows Update', 'alta', '{}', '0x800705B4: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x800705B4 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x80072EE2', '80072EE2', 'Connection Error', 'Erro 0x80072EE2: Erro de conexão', 'Este erro indica que houve um problema de conexão com a internet.', 'Windows Update', 'alta', '{}', '0x80072EE2: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x80072EE2 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x800F081F', '800F081F', 'File Not Found', 'Erro 0x800F081F: Arquivo não encontrado', 'Este erro ocorre quando um arquivo necessário não pode ser encontrado durante a instalação.', 'Windows Update', 'alta', '{}', '0x800F081F: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x800F081F e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x800F0831', '800F0831', 'Update Error', 'Erro 0x800F0831: Erro de atualização', 'Este erro indica que houve um problema ao tentar atualizar o Windows.', 'Windows Update', 'alta', '{}', '0x800F0831: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x800F0831 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x80073712', '80073712', 'Corrupt Files', 'Erro 0x80073712: Arquivos corrompidos', 'Este erro indica que alguns arquivos do sistema estão corrompidos.', 'Windows Update', 'alta', '{}', '0x80073712: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x80073712 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x80240034', '80240034', 'Update Not Found', 'Erro 0x80240034: Atualização não encontrada', 'Este erro ocorre quando a atualização solicitada não pode ser encontrada.', 'Windows Update', 'alta', '{}', '0x80240034: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x80240034 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x80246007', '80246007', 'Download Error', 'Erro 0x80246007: Erro de download', 'Este erro indica que houve um problema ao tentar baixar a atualização.', 'Windows Update', 'alta', '{}', '0x80246007: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x80246007 e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x8024402F', '8024402F', 'Server Error', 'Erro 0x8024402F: Erro de servidor', 'Este erro indica que houve um problema com o servidor de atualização.', 'Windows Update', 'alta', '{}', '0x8024402F: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x8024402F e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now()),
('0x8024401C', '8024401C', 'Connection Timeout', 'Erro 0x8024401C: Tempo de conexão esgotado', 'Este erro indica que a conexão com o servidor de atualização levou muito tempo.', 'Windows Update', 'alta', '{}', '0x8024401C: Como corrigir erro no Windows | WinFixer', 'Descubra o que significa o erro 0x8024401C e siga um diagnóstico passo a passo com soluções verificadas para Windows.', 'published', now(), now());

insert into error_contexts (error_id, name, slug, description, operating_systems, symptoms, created_at) values
((select id from errors where code = '0x80070002'), 'Windows Update', 'windows-update', 'Contexto relacionado a atualizações do Windows.', '{}', '{}', now()),
((select id from errors where code = '0x80070003'), 'Instalação', 'installation', 'Contexto relacionado à instalação de software.', '{}', '{}', now()),
((select id from errors where code = '0x80070005'), 'Ativação', 'activation', 'Contexto relacionado à ativação do Windows.', '{}', '{}', now()),
((select id from errors where code = '0x80070005'), 'Microsoft Store', 'microsoft-store', 'Contexto relacionado à Microsoft Store.', '{}', '{}', now()),
((select id from errors where code = '0x80070005'), 'Inicialização', 'boot', 'Contexto relacionado à inicialização do sistema.', '{}', '{}', now()),
((select id from errors where code = '0x80070005'), 'Driver', 'driver', 'Contexto relacionado a drivers de dispositivos.', '{}', '{}', now()),
((select id from errors where code = '0x80070005'), 'Sistema', 'system', 'Contexto relacionado ao sistema operacional.', '{}', '{}', now());

insert into fixes (error_id, context_id, title, summary, instructions, risk_level, difficulty, source_type, source_url, evidence_score, confidence_level, status, created_at, updated_at) values
((select id from errors where code = '0x80070002'), (select id from error_contexts where slug = 'windows-update'), 'Reparar arquivos do sistema', 'Esta correção tenta reparar arquivos do sistema corrompidos.', 'Execute o comando DISM /Online /Cleanup-Image /RestoreHealth.', 'low', 'easy', 'official', 'https://support.microsoft.com', 50, 'verified', 'published', now(), now()),
((select id from errors where code = '0x80070003'), (select id from error_contexts where slug = 'installation'), 'Verificar espaço em disco', 'Certifique-se de que há espaço suficiente em disco.', 'Verifique as configurações de armazenamento.', 'low', 'easy', 'official', 'https://support.microsoft.com', 50, 'verified', 'published', now(), now()),
((select id from errors where code = '0x80070005'), (select id from error_contexts where slug = 'activation'), 'Reativar Windows', 'Tente reativar o Windows.', 'Vá para Configurações > Atualização e Segurança > Ativação.', 'low', 'easy', 'official', 'https://support.microsoft.com', 50, 'verified', 'published', now(), now()),
((select id from errors where code = '0x80070005'), (select id from error_contexts where slug = 'microsoft-store'), 'Reiniciar Microsoft Store', 'Tente reiniciar a Microsoft Store.', 'Feche e reabra a Microsoft Store.', 'low', 'easy', 'official', 'https://support.microsoft.com', 50, 'verified', 'published', now(), now()),
((select id from errors where code = '0x80070005'), (select id from error_contexts where slug = 'boot'), 'Reparar inicialização', 'Use a ferramenta de reparo de inicialização.', 'Acesse as opções de recuperação do Windows.', 'low', 'easy', 'official', 'https://support.microsoft.com', 50, 'verified', 'published', now(), now()),
((select id from errors where code = '0x80070005'), (select id from error_contexts where slug = 'driver'), 'Atualizar drivers', 'Certifique-se de que todos os drivers estão atualizados.', 'Vá para o Gerenciador de Dispositivos.', 'low', 'easy', 'official', 'https://support.microsoft.com', 50, 'verified', 'published', now(), now()),
((select id from errors where code = '0x80070005'), (select id from error_contexts where slug = 'system'), 'Executar SFC', 'Execute o comando sfc /scannow.', 'Abra o Prompt de Comando como administrador.', 'low', 'easy', 'official', 'https://support.microsoft.com', 50, 'verified', 'published', now(), now());